// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgCHjG6CeMWfPiAsBlzGWWsuRpRrwc19M',
    appId: '1:813827493873:web:0886d2efb45ca199693e50',
    messagingSenderId: '813827493873',
    projectId: 'mobile-aplication-34f11',
    authDomain: 'mobile-aplication-34f11.firebaseapp.com',
    storageBucket: 'mobile-aplication-34f11.appspot.com',
    measurementId: 'G-G40X3LYR3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU26frPn9Yz2FK25_xhR2xnLjYuWGMRBI',
    appId: '1:813827493873:android:856c35b2d95113f8693e50',
    messagingSenderId: '813827493873',
    projectId: 'mobile-aplication-34f11',
    storageBucket: 'mobile-aplication-34f11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9tAdB5ozGzveYzOEm_gOKC4E59HhOM88',
    appId: '1:813827493873:ios:c37bb45c848ee540693e50',
    messagingSenderId: '813827493873',
    projectId: 'mobile-aplication-34f11',
    storageBucket: 'mobile-aplication-34f11.appspot.com',
    iosBundleId: 'com.example.instagramCloning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tAdB5ozGzveYzOEm_gOKC4E59HhOM88',
    appId: '1:813827493873:ios:c37bb45c848ee540693e50',
    messagingSenderId: '813827493873',
    projectId: 'mobile-aplication-34f11',
    storageBucket: 'mobile-aplication-34f11.appspot.com',
    iosBundleId: 'com.example.instagramCloning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgCHjG6CeMWfPiAsBlzGWWsuRpRrwc19M',
    appId: '1:813827493873:web:a2d6966ad78fb0fc693e50',
    messagingSenderId: '813827493873',
    projectId: 'mobile-aplication-34f11',
    authDomain: 'mobile-aplication-34f11.firebaseapp.com',
    storageBucket: 'mobile-aplication-34f11.appspot.com',
    measurementId: 'G-B1S3CDB27J',
  );

}